#!/bin/bash

BIGSTITCHER_FOLDER="BigStitcher-Spark"
REPO_URL="https://github.com/JaneliaSciComp/BigStitcher-Spark.git"

if [ -d "$FOLDER" ]; then
    echo "The folder '$BIGSTITCHER_FOLDER' already exists."
else
    echo "Cloning repository..."
    git clone "$REPO_URL"
fi

#cd /code/BigStitcher-Spark
cd BigStitcher-Spark

#create output directory with multires folders
./create-fusion-container-fromfatjar -x /data/bigstitcher.xml -o /results/$OUTPUT_PATH -d UINT16 --preserveAnisotropy --multiRes

#run fusion
./affine-fusion-container-fromfatjar -o /results/$OUTPUT_PATH -s ZARR
