#!/usr/bin/env bash
set -ex

# Activate stitch env to solve argschema python version bug
source /opt/conda/etc/profile.d/conda.sh
conda activate smartspim_fusion

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u run_capsule.py "$@"
