#!/bin/bash

#cd /code/BigStitcher-Spark
cd BigStitcher-Spark

#create output directory with multires folders
./create-fusion-container-fromfatjar -x /data/bigstitcher.xml -o /results/$OUTPUT_PATH -d UINT16 --preserveAnisotropy --multiRes

#run fusion
./affine-fusion-container-fromfatjar -o /results/$OUTPUT_PATH -s ZARR
